# fly.toml app configuration file generated for server-b on 2024-09-11T00:43:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-b'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
